import type {Metadata} from "next";

import {Encode_Sans} from "next/font/google";

import "./globals.css";
import Link from "next/link";

export const encodeSans = Encode_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Estudio VArq",
  description: "Generated by appncy",
};

export default async function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="es">
      <body className={`${encodeSans.className} bg-white text-black`}>
        <header className="flex items-center justify-between gap-20 bg-white px-96 py-5 text-black">
          <img alt="Logo" src="./logo.png" width="250px" />
          <ul className="flex gap-10 text-[#001F3D]">
            <li>
              <Link href="/">Nosotros</Link>
            </li>
            <li>
              <Link href="/">Servicios</Link>
            </li>
            <li>
              <Link href="/">Casas</Link>
            </li>
            <li>
              <Link href="/">Contactanos</Link>
            </li>
          </ul>
        </header>
        {children}
        <footer className="text-center leading-[4rem] opacity-70">estudiovarq-website</footer>
      </body>
    </html>
  );
}
